name: My First Workflow

on: push
env:
  ARI: "IR"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show push
        run: echo "Push successful"
      - name: Show name
        run: echo "${ARI} "
      - name: Show name
        run: echo "$ARI "
      - name: Show secret
        run: echo "${secret.ARIF} "
        
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Show test
        run: echo " tested"