name: My First Workflow

on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show push
        run: echo "Push successful"
      - name: Show name
        run: ls